### ISSUE TITLE
sign in with persona, but persona scheduled for shutdown

### ISSUE THREAD

**Issue by shadiakiki1986** [cowbell/sharedrop#47]
On the persona website it says that they're scheduled for shutdown by end of november

**Comment by shadiakiki1986** [comment]
Maybe passwordless.net would be a good alternative?

**Comment by GreenBeard** [comment]
Persona is now officially down.

**Comment by szimek** [comment]
Has anyone actually tried passwordless.net before? The only thing I need is an email address that is verified by a third-party. Persona was pretty awesome for that...

There are also some privacy/security concerns about using IP addresses for logged out users, so maybe someone has some other idea how to identify users/devices?

**Comment by shadiakiki1986** [comment]
I've never tried passwordless.net before. Just read about it on the [Identity/Persona Shutdown Guidelines for Reliers](https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers#Passwordless_Email_Login) wiki page

**Comment by thecakeisalie25** [comment]
Maybe just allow users to upload an image and store it in their cache instead of server-side? and use webrtc again to transfer it to the other users?
