### ISSUE TITLE
QR code Sharing URL

### ISSUE THREAD

**Issue by avinayak** [cowbell/sharedrop#51]
It's easier to share if there is a qr code generator and reader on mobile devices.

**Comment by jrruethe** [comment]
I agree completely, this would be a great enhancement

**Comment by szimek** [comment]
In case of local sharing the url doesn't change - it's always `sharedrop.io`. In case of sharing between networks, what's the advantage of using QR code over copying it from a text input? You still need to send it using an email or some app to another person.

**Comment by jrruethe** [comment]
An example would be if I am in front of a computer with ethernet and my phone is on 4G. It would be much easier to scan the screen than type in a number. Just because the devices are physically co-located doesn't mean the devices are on the same LAN.

**Comment by szimek** [comment]
@jrruethe Looks like a valid (though probably not very common) case ;) 

If anyone wants to create a PR, they are very welcome. There's an add-on for this: https://github.com/AlexeiDrake/ember-qrcode, so it shouldn't be hard.

**Comment by recurza** [comment]
Hey, I'd like to take a crack at this. Haven't used ember before, but will try and see

**Comment by szimek** [comment]
@recurza Good luck! The code is rather old and most likely is not according to todays Ember standards :/

I started rewriting the whole thing in ES6 (https://github.com/cowbell/sharedrop/tree/es6), but can't find time to finish it.

**Comment by recurza** [comment]
Oh! I'd be interested in helping with the ES6 transition instead. Will go take a look

**Comment by DJCrashdummy** [comment]
i guess this can be closed, or am i wrong?

**Comment by szimek** [comment]
Yeah, thanks!
