### ISSUE TITLE
[Suggestion] Private Rooms and Voice Chats

### ISSUE THREAD

**Issue by Edward-Stryfe** [cowbell/sharedrop#54]
So what about having the option for private rooms where the creator decides on a password and anyone with the password can access the room. In addition since the mozilla program persona has been shut down it might be best to just do something similar to Candid where your id will be a serious of words or names of animals. 

As for voice chat there is a very good WebRTC powered application https://github.com/mikeal/roll-call that could be easily implemented into the program. It works off of a room based protocol as well so you can assign the room of the voice channel to match that of the share space.

**Comment by anonno** [comment]
Hi have been looking for others interesting in hosting files... 
I run a 12TB server now & a good VPS to help/play around with.. 

I also been admin on private trackers... http://imgur.com/a/p2YtR

**Comment by szimek** [comment]
It's out of scope of this project :/
