### ISSUE TITLE
how to deploy sharedrop on VPS?

### ISSUE THREAD

**Issue by chinobing** [cowbell/sharedrop#72]
how to deploy sharedrop on VPS?

**Comment by szimek** [comment]
More or less as described in the README.

You'll need to set up Firebase, generate a random secret and then set the following environment variables:
```
FIREBASE_SECRET: <from your Firebase config>
FIREBASE_URL: <from your Firebase config>
SECRET: <some random string>
```
Run `yarn` to install all dependencies and `yarn build` to generate the app into `dist` folder.

**Comment by chinobing** [comment]
thanks alot.
