### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Loilo** [cowbell/sharedrop#75]
Let me start with mentioning that I **love** to see this repository being worked on again. It's one of the coolest web apps I've seen in a while. I'd be interested if you have any concrete plans for future features of this project?

New web APIs from the recent years have made me want to fork or reimplement ShareDrop several times, but I have never found the time to do so.

I'm particularly curious if you're planning to integrate features related to PWAs or the Web Share Target API?

**Comment by szimek** [comment]
Thanks!

> New web APIs from the recent years have made me want to fork or reimplement ShareDrop several times, but I have never found the time to do so.

That's exactly my problem :) 

I'd like to rewrite it in (p)React, add service workers, replace PeerJS library with something modern (e.g. simple-peer), maybe even replace the current custom transfer protocol with webtorrent, look into improving transfer speed, fix bugs, improve error handling, figure out how to make it work on iOS etc. Web Share Target API is something I haven't looked into at all yet, but it seems like a nice fit for ShareDrop.

Unfortunately, I have no idea when/if I find time to work on that.

**Comment by Loilo** [comment]
The old, ubiquitous problem I guess. 😁

**Comment by simonesestito** [comment]
+1 for Service Worker and Progressive Web App. It would be awesome to have sharedrop installable as PWA on almost every device and offline too
