### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by meyermarcel** [cowbell/sharedrop#77]
Visiting https://www.sharedrop.io shows

<img width="526" alt="Screenshot 2019-05-22 at 21 48 23" src="https://user-images.githubusercontent.com/3398801/58203854-6115a000-7cdb-11e9-929d-7ca5eae7ee5d.png">

**Comment by szimek** [comment]
Thank you for reporting it! I really should set up some monitoring there... 

No idea what happened, I just restarted the app on Heroku and it works again.
