### ISSUE TITLE
npm ERR! missing script: dev

### ISSUE THREAD

**Issue by d1mf** [cowbell/sharedrop#85]
[root@centos8 sharedrop]# npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-18T20_55_42_031Z-debug.log

I install use README. For step pm run dev I have this error

**Comment by szimek** [comment]
Try `npm run develop` and let me know if it works. If it does, I'll update the README.

**Comment by d1mf** [comment]
npm run develop - working

**Comment by d1mf** [comment]
![Screenshot_47](https://user-images.githubusercontent.com/10393074/77057583-d83fc180-69dc-11ea-990c-99e88d53802f.png)
Now I see only this message on load website.  Maybe problem connect to firebase? Where I can check logs? Thanks

**Comment by szimek** [comment]
Please provide error messages from Dev Tools console.

**Comment by szimek** [comment]
I've updated the README file, so now it correctly describes available commands. If you're getting some JS error, please open a new issue.
