### ISSUE TITLE
Support text sharing

### ISSUE THREAD

**Issue by wanderseeme** [cowbell/sharedrop#86]
Please add a feature of text sharing, e.g., right-click on an icon to popup a text sharing message box to share.
This feature is inspired by Snapdrop (https://snapdrop.net/).

**Comment by nashbridges** [comment]
This is a duplicate of https://github.com/cowbell/sharedrop/issues/80.

**Comment by szimek** [comment]
I'm closing this one as a duplicate of #80.

**Comment by ethanneff** [comment]
use https://snapdrop.net/ instead. can share files and text
