### ISSUE TITLE
Could you please write the documentation for development clearly.

### ISSUE THREAD

**Issue by prasadbobby** [cowbell/sharedrop#95]
I'm a beginner and student. Could you please try to write the documentation for development clearly.  What was the secret key at .env file. There is no documentation for that.
![Annotation 2020-10-17 011845](https://user-images.githubusercontent.com/57008950/96302646-c677d880-1016-11eb-80fc-7108266b8f53.png)

![image](https://user-images.githubusercontent.com/57008950/96302780-f626e080-1016-11eb-99db-faef35b21f05.png)
👆👆👆👆This is the error.

**Comment by szimek** [comment]
Hi! Does it work when you run `yarn develop`?

**Comment by prasadbobby** [comment]
Noo Sir.. Please specify the whole documentation on it or send me through
email.

**Comment by szimek** [comment]
There is a documentation for running it locally already: https://github.com/cowbell/sharedrop#how-to-set-it-up-for-local-development Make sure that the Firebase related environment variables are set correctly. 

Also, I've never tried running this project on Windows, so there might be some Windows specific bugs there. If you think everything is set up correctly, but it still doesn't work, you could try to run it on some Linux system, e.g. using Docker.

**Comment by prasadbobby** [comment]
yeah that's not an with windows i think. i have firebase related doubts.
What was the line no:2,5 and 6
[image: Annotation 2020-10-17 011845.png]

**Comment by prasadbobby** [comment]
yeah that's not an issue with windows i think. i have firebase related doubts.
What was the line no:2,5 and 6
![Annotation 2020-10-17 011845](https://user-images.githubusercontent.com/57008950/96348154-490aa180-10c4-11eb-90ce-b7b4e28030c3.png)

**Comment by szimek** [comment]
I'm using something that Google calls "Legacy credentials", so it might be impossible to create these.

Unfortunately, I don't really have time now to look into what would be needed to update Firebase to a more recent version :/ If anyone wants to do PR, they are very, very welcome.
